# Used to store server-related config file on the client
# Set it to a single value on different servers if you want them to share config
server_id = "70078af1-13e4-4811-a21d-3675d433bfab"
default_language = "en_us"
debug = false
disable_crowdin = false
check_for_updates = true

[host]
ip = "139.99.124.9"
port = 25560

[voice]
# Supported sample rates:
# 8000
# 12000
# 24000
# 48000
sample_rate = 48000
keep_alive_timeout_ms = 15000
mtu_size = 1024
client_mod_required = false
client_mod_required_check_timeout_ms = 3000

[voice.proximity]
distances = [8, 16, 20]
default_distance = 20

[voice.opus]
# Opus application mode
# Supported values: VOIP, AUDIO, RESTRICTED_LOWDELAY
# Default is VOIP
mode = "VOIP"
# Opus bitrate
# Supported values: -1000 (auto), -1 (max), [500-512_000]
# Default is -1000
bitrate = -1000

[voice.weights]


